# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JourneyCompetencyTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JourneyCompetencyTest
pod 'Alamofire', '~> 4.7'
   pod 'ObjectMapper'
   pod 'SVProgressHUD'
  target 'JourneyCompetencyTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JourneyCompetencyTestUITests' do
    # Pods for testing
  end

end
